notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - docker

language: node_js
node_js:
  - 8

install:
  - npm install
  - npm install -g codecov

cache:
  directories:
    - "node_modules"

script:
  - npm test
  - codecov

after_success:
  - npm run build
  - bash Dockerbuild.sh

deploy:
  - provider: pages
    local-dir: dist
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    fqdn: jsboilerplate-webvuejs.aikaka.net
  - provider: script
    script: bash Dockerpush.sh
  on:
    branch: master
